# Usar Usuario, Clave y Base de Datos con su propia información, por ejemplo:
# POSTGRES_USER: gonzalezj       --->>> su apellido más la primera letra de su nombre
# POSTGRES_PASSWORD: Jesus556    --->>> una clave que ud. elija
# POSTGRES_DB: Prueba            --->>> la Base de Datos deberá tener el nombre de Prueba 
services:
  mysql_container:
    image: mysql:5.7
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
      MYSQL_USER: Emma15
      MYSQL_PASSWORD: emmapass
    ports:
      - "3306:3306"
    networks:
      - appnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    restart: always
    ports:
      - "8086:80"
    environment:
      PMA_HOST: mysql_container
      PMA_USER: Emma15
      PMA_PASSWORD: emmapass
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
